apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.Values.serviceName}}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{.Values.serviceName}}
    template:
        metadata:
            labels:
                app: {{.Values.serviceName}}
        spec:
            containers:
                - name: php
                  image: localhost:32000/{{.Values.serviceName}}:latest
                  env:
                      - name: PHP_IDE_CONFIG
                        value: serverName={{.Values.serviceName}}
                  volumeMounts:
                      - name: code
                        mountPath: /var/www/app
                      - name: xdebug-config
                        mountPath: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
                        subPath: xdebug.ini


                - name: nginx
                  image: nginx:1.27-alpine
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: code
                        mountPath: /var/www/app
                      - name: nginx-conf
                        mountPath: /etc/nginx/conf.d/default.conf
                        subPath: default.conf

            volumes:
                - name: code
                  hostPath:
                      path: {{.Values.hostPath}}
                - name: xdebug-config
                  configMap:
                      name: {{.Values.serviceName}}-php-config
                - name: nginx-conf
                  configMap:
                      name: {{.Values.serviceName}}-nginx-config
