apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{.Values.serviceName}}-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - host: {{.Values.serviceName}}.local
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{.Values.serviceName}}
                            port:
                                number: 80